In [1]:
import numpy as np

In [6]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr**arr

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489], dtype=int32)

In [15]:
arr_2d = arr.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr_2d**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [17]:
arr_1d = np.array([1,2,3])
arr_2d*arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [19]:
arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.sin(arr_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [21]:
np.log(arr_1d)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [23]:
np.exp(arr_2d)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [26]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
np.exp(arr_1d)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [28]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [29]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [34]:
np.insert(arr_2d,3,1002)

array([   1,    2,    3, 1002,    4,    5,    6,    7,    8,    9])

In [39]:
np.delete(arr_2d,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.append(arr,1241251)

array([      1,       2,       3,       4,       5,       6,       7,
             8,       9, 1241251])

In [53]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [58]:
np.where(arr>3,100,arr)

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [60]:
np.where(arr_2d <=6,0,arr_2d)

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

In [2]:
import numpy as np
import pandas as pd

In [4]:
label = ['a','b','c']
x = [100,200,300]

In [5]:
pd.Series(data=x)

0    100
1    200
2    300
dtype: int64

In [6]:
pd.Series (data = x,index = label)

a    100
b    200
c    300
dtype: int64

In [7]:
pd.Series(x,label)

a    100
b    200
c    300
dtype: int64

In [17]:
a = [i for i in range(1,5)]
b = [i for i in range(5,9)]
c = [i for i in range(9,13)]

In [24]:
pd.DataFrame(data = [a,b,c], index = 'et dah bacang'.split(),columns= 'Ini Panda apa Numpy'.split())


Ini  Panda  apa  Numpy
et        1      2    3      4
dah       5      6    7      8
bacang    9     10   11     12

In [22]:
x_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [23]:
pd.DataFrame(x_list)

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [25]:
pd.Series(data = x_list,index=label)

a       [1, 2, 3, 4]
b       [5, 6, 7, 8]
c    [9, 10, 11, 12]
dtype: object

In [26]:
pd.Series(x_list,label)

a       [1, 2, 3, 4]
b       [5, 6, 7, 8]
c    [9, 10, 11, 12]
dtype: object

In [27]:
pd.Series(x_list)

0       [1, 2, 3, 4]
1       [5, 6, 7, 8]
2    [9, 10, 11, 12]
dtype: object

In [30]:
d = {'a':10,'b':20,'c':30}

In [31]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [32]:
from numpy.random import randn
np.random.seed(10)

In [33]:
df = pd.DataFrame(randn(10,10), index= 'A B C D E F G H I J'.split(), columns= 'K L M N O P Q R S T'.split())

In [34]:
df

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J  1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   

          R         S         T  
A  0.108549  0.004291 -0.174600  
B  0.135137  1.484537 -1.079805  
C  1.397996 -0.271248  0.613204  
D -0.337632  1.256472 -0.731970  
E  0.312170  0.565153 -0.147420  
F  0.917459 -0.112272 -0.362180  
G -1.418556 -0.362499 -0.121906  
H  0.620601 -1.045133 -0.798009  
I  0.393341  0.217265 -1.994394  
J  0.089588  0.826999 -1.954512

In [36]:
my_d = {'a':[1,2,3,4],'b':[5,6,7,8],'c':[9,10,11,12]}
pd.DataFrame(my_d,index='W X Y Z'.split())

a  b   c
W  1  5   9
X  2  6  10
Y  3  7  11
Z  4  8  12

In [40]:
df['O']

A    0.621336
B    0.228630
C    1.123691
D    1.308473
E   -0.804591
F    0.842225
G   -0.081122
H    0.314754
I   -0.065848
J    0.711959
Name: O, dtype: float64

In [41]:
df['O'][8]

-0.06584784771120117

In [42]:
df['O'][1:9]

B    0.228630
C    1.123691
D    1.308473
E   -0.804591
F    0.842225
G   -0.081122
H    0.314754
I   -0.065848
Name: O, dtype: float64

In [43]:
df.O

A    0.621336
B    0.228630
C    1.123691
D    1.308473
E   -0.804591
F    0.842225
G   -0.081122
H    0.314754
I   -0.065848
J    0.711959
Name: O, dtype: float64

In [44]:
df['tambahan']=[1,2,3,4,5,6,7,8,9,10]

In [45]:
df

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J  1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   

          R         S         T  tambahan  
A  0.108549  0.004291 -0.174600         1  
B  0.135137  1.484537 -1.079805         2  
C  1.397996 -0.271248  0.613204         3  
D -0.337632  1.256472 -0.731970         4  
E  0.312170  0.565153 -0.147420         5  
F  0.917459 -0.112272 -0.362180         6  
G -1.418556 -0.362499 -0.121906         7  
H  0.620601 -1.045133 -0.798009         8  
I  0.393341  0.217265 -1.994394         9  
J  0.089588  0.826999 -1.954512        10

In [46]:
df.tambahan

A     1
B     2
C     3
D     4
E     5
F     6
G     7
H     8
I     9
J    10
Name: tambahan, dtype: int64

In [47]:
df.min

<bound method NDFrame._add_numeric_operations.<locals>.min of           K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J  1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   

          R         S         T  tambahan  
A  0.108549  0.004291 -0.174600         1  
B  0.135137  1.484537 -1

In [52]:
df['tambahan']

A     1
B     2
C     3
D     4
E     5
F     6
G     7
H     8
I     9
J    10
Name: tambahan, dtype: int64

In [54]:
df[['O','tambahan']]

O  tambahan
A  0.621336         1
B  0.228630         2
C  1.123691         3
D  1.308473         4
E -0.804591         5
F  0.842225         6
G -0.081122         7
H  0.314754         8
I -0.065848         9
J  0.711959        10

In [57]:
df.loc['B']

K           0.433026
L           1.203037
M          -0.965066
N           1.028274
O           0.228630
P           0.445138
Q          -1.136602
R           0.135137
S           1.484537
T          -1.079805
tambahan    2.000000
Name: B, dtype: float64

In [58]:
df.loc['B':'E']

K         L         M         N         O         P         Q  \
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   

          R         S         T  tambahan  
B  0.135137  1.484537 -1.079805         2  
C  1.397996 -0.271248  0.613204         3  
D -0.337632  1.256472 -0.731970         4  
E  0.312170  0.565153 -0.147420         5

In [59]:
df.iloc[1]

K           0.433026
L           1.203037
M          -0.965066
N           1.028274
O           0.228630
P           0.445138
Q          -1.136602
R           0.135137
S           1.484537
T          -1.079805
tambahan    2.000000
Name: B, dtype: float64

In [64]:
df.iloc[1:5:2]

K         L         M         N         O         P         Q  \
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
D -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   

          R         S         T  tambahan  
B  0.135137  1.484537 -1.079805         2  
D -0.337632  1.256472 -0.731970         4

In [65]:
df.iloc[:,0:2]

K         L
A  1.331587  0.715279
B  0.433026  1.203037
C -1.977728 -1.743372
D -0.267317 -0.549309
E  0.660232 -0.350872
F -0.025905  0.289094
G -0.232182 -0.501729
H  0.319356  0.460903
I  1.985085  1.744814
J  1.107708  0.244544

In [67]:
df.iloc[1,3]

1.028274077982704

In [70]:
df.iloc[[0,3]]

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
D -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   

          R         S        T  tambahan  
A  0.108549  0.004291 -0.17460         1  
D -0.337632  1.256472 -0.73197         4

In [71]:
df>0

K      L      M      N      O      P      Q      R      S      T  \
A   True   True  False  False   True  False   True   True   True  False   
B   True   True  False   True   True   True  False   True   True  False   
C  False  False   True   True   True   True   True   True  False   True   
D  False  False   True  False   True   True   True  False   True  False   
E   True  False  False  False  False  False  False   True   True  False   
F  False   True  False   True   True   True   True   True  False  False   
G  False  False   True  False  False  False   True  False  False  False   
H   True   True  False   True   True   True  False   True  False  False   
I   True   True  False  False  False  False  False   True   True  False   
J   True   True  False  False   True   True  False   True   True  False   

   tambahan  
A      True  
B      True  
C      True  
D      True  
E      True  
F      True  
G      True  
H      True  
I      True  
J      True

In [72]:
df[df>0]

K         L         M         N         O         P         Q  \
A  1.331587  0.715279       NaN       NaN  0.621336       NaN  0.265512   
B  0.433026  1.203037       NaN  1.028274  0.228630  0.445138       NaN   
C       NaN       NaN  0.266070  2.384967  1.123691  1.672622  0.099149   
D       NaN       NaN  0.132708       NaN  1.308473  0.195013  0.400210   
E  0.660232       NaN       NaN       NaN       NaN       NaN       NaN   
F       NaN  0.289094       NaN  0.708160  0.842225  0.203581  2.394704   
G       NaN       NaN  1.128785       NaN       NaN       NaN  1.046183   
H  0.319356  0.460903       NaN  0.989072  0.314754  2.467651       NaN   
I  1.985085  1.744814       NaN       NaN       NaN       NaN       NaN   
J  1.107708  0.244544       NaN       NaN  0.711959  0.918269       NaN   

          R         S         T  tambahan  
A  0.108549  0.004291       NaN         1  
B  0.135137  1.484537       NaN         2  
C  1.397996       NaN  0.613204         3  
D       NaN  1.256472       NaN         4  
E  0.312170  0.565153       NaN         5  
F  0.917459       NaN       NaN         6  
G       NaN       NaN       NaN         7  
H  0.620601       NaN       NaN         8  
I  0.393341  0.217265       NaN         9  
J  0.089588  0.826999       NaN        10

In [76]:
df[df['R']>0]

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J  1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   

          R         S         T  tambahan  
A  0.108549  0.004291 -0.174600         1  
B  0.135137  1.484537 -1.079805         2  
C  1.397996 -0.271248  0.613204         3  
E  0.312170  0.565153 -0.147420         5  
F  0.917459 -0.112272 -0.362180         6  
H  0.620601 -1.045133 -0.798009         8  
I  0.393341  0.217265 -1.994394         9  
J  0.089588  0.826999 -1.954512        10

In [74]:
df[df['K']>0]['P']

A   -0.720086
B    0.445138
E   -0.212698
H    2.467651
I   -2.131712
J    0.918269
Name: P, dtype: float64

In [77]:
import numpy as np
import pandas as pd

In [81]:
df.loc['new']=[1,2,3,4,5,6,7,8,9,10,11]
df

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T  tambahan  
A    0.108549  0.004291  -0.174600         1  
B    0.135137  1.484537  -1.079805         2  
C    1.397996 -0.271248   0.613204         3  
D   -0.337632  1.256472  -0.731970         4  
E    0.312170  0.565153  -0.147420         5  
F    0.917459 -0.112272  -0.362180         6  
G   -1.418556 -0.362499  -0.121906         7  
H    0.620601 -1.045133  -0.798009         8  
I    0.393341  0.217265  -1.994394         9  
J    0.089588  0.826999  -1.954512        10  
new  8.000000  9.000000  10.000000        11

In [84]:
df['new'] = df['K']+df['tambahan']

In [85]:
df

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T  tambahan        new  
A    0.108549  0.004291  -0.174600         1   2.331587  
B    0.135137  1.484537  -1.079805         2   2.433026  
C    1.397996 -0.271248   0.613204         3   1.022272  
D   -0.337632  1.256472  -0.731970         4   3.732683  
E    0.312170  0.565153  -0.147420         5   5.660232  
F    0.917459 -0.112272  -0.362180         6   5.974095  
G   -1.418556 -0.362499  -0.121906         7   6.767818  
H    0.620601 -1.045133  -0.798009         8   8.319356  
I    0.393341  0.217265  -1.994394         9  10.985085  
J    0.089588  0.826999  -1.954512        10  11.107708  
new  8.000000  9.000000  10.000000        11  12.000000

In [100]:
df.drop('new',axis=1)

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T  tambahan  
A    0.108549  0.004291  -0.174600         1  
B    0.135137  1.484537  -1.079805         2  
C    1.397996 -0.271248   0.613204         3  
D   -0.337632  1.256472  -0.731970         4  
E    0.312170  0.565153  -0.147420         5  
F    0.917459 -0.112272  -0.362180         6  
G   -1.418556 -0.362499  -0.121906         7  
H    0.620601 -1.045133  -0.798009         8  
I    0.393341  0.217265  -1.994394         9  
J    0.089588  0.826999  -1.954512        10  
new  8.000000  9.000000  10.000000        11

In [101]:
df

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T  tambahan        new  
A    0.108549  0.004291  -0.174600         1   2.331587  
B    0.135137  1.484537  -1.079805         2   2.433026  
C    1.397996 -0.271248   0.613204         3   1.022272  
D   -0.337632  1.256472  -0.731970         4   3.732683  
E    0.312170  0.565153  -0.147420         5   5.660232  
F    0.917459 -0.112272  -0.362180         6   5.974095  
G   -1.418556 -0.362499  -0.121906         7   6.767818  
H    0.620601 -1.045133  -0.798009         8   8.319356  
I    0.393341  0.217265  -1.994394         9  10.985085  
J    0.089588  0.826999  -1.954512        10  11.107708  
new  8.000000  9.000000  10.000000        11  12.000000

In [103]:
df.drop('tambahan',axis = 1)

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T        new  
A    0.108549  0.004291  -0.174600   2.331587  
B    0.135137  1.484537  -1.079805   2.433026  
C    1.397996 -0.271248   0.613204   1.022272  
D   -0.337632  1.256472  -0.731970   3.732683  
E    0.312170  0.565153  -0.147420   5.660232  
F    0.917459 -0.112272  -0.362180   5.974095  
G   -1.418556 -0.362499  -0.121906   6.767818  
H    0.620601 -1.045133  -0.798009   8.319356  
I    0.393341  0.217265  -1.994394  10.985085  
J    0.089588  0.826999  -1.954512  11.107708  
new  8.000000  9.000000  10.000000  12.000000

In [105]:
df.drop('new')
df

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T  tambahan        new  
A    0.108549  0.004291  -0.174600         1   2.331587  
B    0.135137  1.484537  -1.079805         2   2.433026  
C    1.397996 -0.271248   0.613204         3   1.022272  
D   -0.337632  1.256472  -0.731970         4   3.732683  
E    0.312170  0.565153  -0.147420         5   5.660232  
F    0.917459 -0.112272  -0.362180         6   5.974095  
G   -1.418556 -0.362499  -0.121906         7   6.767818  
H    0.620601 -1.045133  -0.798009         8   8.319356  
I    0.393341  0.217265  -1.994394         9  10.985085  
J    0.089588  0.826999  -1.954512        10  11.107708  
new  8.000000  9.000000  10.000000        11  12.000000

In [106]:
df.drop('tambahan',axis=1)

K         L         M         N         O         P         Q  \
A    1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B    0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C   -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
D   -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013  0.400210   
E    0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F   -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G   -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H    0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I    1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J    1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   
new  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000  7.000000   

            R         S          T        new  
A    0.108549  0.004291  -0.174600   2.331587  
B    0.135137  1.484537  -1.079805   2.433026  
C    1.397996 -0.271248   0.613204   1.022272  
D   -0.337632  1.256472  -0.731970   3.732683  
E    0.312170  0.565153  -0.147420   5.660232  
F    0.917459 -0.112272  -0.362180   5.974095  
G   -1.418556 -0.362499  -0.121906   6.767818  
H    0.620601 -1.045133  -0.798009   8.319356  
I    0.393341  0.217265  -1.994394  10.985085  
J    0.089588  0.826999  -1.954512  11.107708  
new  8.000000  9.000000  10.000000  12.000000

In [107]:
df.drop('new',axis=1,inplace=True)

In [132]:
df

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   
J  1.107708  0.244544 -0.061912 -0.753893  0.711959  0.918269 -0.482093   

          R         S         T  
A  0.108549  0.004291 -0.174600  
B  0.135137  1.484537 -1.079805  
C  1.397996 -0.271248  0.613204  
E  0.312170  0.565153 -0.147420  
F  0.917459 -0.112272 -0.362180  
G -1.418556 -0.362499 -0.121906  
H  0.620601 -1.045133 -0.798009  
I  0.393341  0.217265 -1.994394  
J  0.089588  0.826999 -1.954512

In [138]:
df.drop('J',axis = 0,inplace=True)
df

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   

          R         S         T  
A  0.108549  0.004291 -0.174600  
B  0.135137  1.484537 -1.079805  
C  1.397996 -0.271248  0.613204  
E  0.312170  0.565153 -0.147420  
F  0.917459 -0.112272 -0.362180  
G -1.418556 -0.362499 -0.121906  
H  0.620601 -1.045133 -0.798009  
I  0.393341  0.217265 -1.994394

In [140]:
df.drop('E',axis = 0)

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   

          R         S         T  
A  0.108549  0.004291 -0.174600  
B  0.135137  1.484537 -1.079805  
C  1.397996 -0.271248  0.613204  
F  0.917459 -0.112272 -0.362180  
G -1.418556 -0.362499 -0.121906  
H  0.620601 -1.045133 -0.798009  
I  0.393341  0.217265 -1.994394

In [141]:
df

K         L         M         N         O         P         Q  \
A  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086  0.265512   
B  0.433026  1.203037 -0.965066  1.028274  0.228630  0.445138 -1.136602   
C -1.977728 -1.743372  0.266070  2.384967  1.123691  1.672622  0.099149   
E  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140   
F -0.025905  0.289094 -0.539879  0.708160  0.842225  0.203581  2.394704   
G -0.232182 -0.501729  1.128785 -0.697810 -0.081122 -0.529296  1.046183   
H  0.319356  0.460903 -0.215790  0.989072  0.314754  2.467651 -1.508321   
I  1.985085  1.744814 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831   

          R         S         T  
A  0.108549  0.004291 -0.174600  
B  0.135137  1.484537 -1.079805  
C  1.397996 -0.271248  0.613204  
E  0.312170  0.565153 -0.147420  
F  0.917459 -0.112272 -0.362180  
G -1.418556 -0.362499 -0.121906  
H  0.620601 -1.045133 -0.798009  
I  0.393341  0.217265 -1.994394

In [142]:
df.drop('L',axis=1,inplace=True)

In [143]:
df

K         M         N         O         P         Q         R  \
A  1.331587 -1.545400 -0.008384  0.621336 -0.720086  0.265512  0.108549   
B  0.433026 -0.965066  1.028274  0.228630  0.445138 -1.136602  0.135137   
C -1.977728  0.266070  2.384967  1.123691  1.672622  0.099149  1.397996   
E  0.660232 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140  0.312170   
F -0.025905 -0.539879  0.708160  0.842225  0.203581  2.394704  0.917459   
G -0.232182  1.128785 -0.697810 -0.081122 -0.529296  1.046183 -1.418556   
H  0.319356 -0.215790  0.989072  0.314754  2.467651 -1.508321  0.620601   
I  1.985085 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831  0.393341   

          S         T  
A  0.004291 -0.174600  
B  1.484537 -1.079805  
C -0.271248  0.613204  
E  0.565153 -0.147420  
F -0.112272 -0.362180  
G -0.362499 -0.121906  
H -1.045133 -0.798009  
I  0.217265 -1.994394

In [144]:
df.reset_index

<bound method DataFrame.reset_index of           K         M         N         O         P         Q         R  \
A  1.331587 -1.545400 -0.008384  0.621336 -0.720086  0.265512  0.108549   
B  0.433026 -0.965066  1.028274  0.228630  0.445138 -1.136602  0.135137   
C -1.977728  0.266070  2.384967  1.123691  1.672622  0.099149  1.397996   
E  0.660232 -0.939433 -0.489337 -0.804591 -0.212698 -0.339140  0.312170   
F -0.025905 -0.539879  0.708160  0.842225  0.203581  2.394704  0.917459   
G -0.232182  1.128785 -0.697810 -0.081122 -0.529296  1.046183 -1.418556   
H  0.319356 -0.215790  0.989072  0.314754  2.467651 -1.508321  0.620601   
I  1.985085 -1.856185 -0.222774 -0.065848 -2.131712 -0.048831  0.393341   

          S         T  
A  0.004291 -0.174600  
B  1.484537 -1.079805  
C -0.271248  0.613204  
E  0.565153 -0.147420  
F -0.112272 -0.362180  
G -0.362499 -0.121906  
H -1.045133 -0.798009  
I  0.217265 -1.994394  >